version: '3.8'

services:
  research-brief-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    env_file:
      - .env
    # Remove volume mounts that override container code
    # volumes:
    #   - ./app:/app/app
    #   - ./research_assistant.db:/app/research_assistant.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 